### ISSUE TITLE
Does this plugin also enable circular routing for payments?

### ISSUE THREAD

**Issue by jalbstmeijer** [giovannizotta/circular#16]
Hi,

Want to be able to create multiple sub wallets on my Lightning node (raspiblitz) running CLN (c-lightning) and be able do payments between those wallets.

It seems LND has a configuration option for this and looking for a similar option on CLN (c-lightning)

https://community.getumbrel.com/t/umbrel-lnbits-app-description-and-basic-use/70

"To be able to have free fee, internal txs between your LNDhub LNbits wallets, add this line in your lnd.conf file: allow-circular-route=1"

Gr, J

**Comment by giovannizotta** [comment]
Hi @jalbstmeijer, no this plugin is not what you are looking for. `circular` is used as a tool to rebalance CLN nodes. You should look at lnbits, since their website says that they also run on CLN.

**Comment by jalbstmeijer** [comment]
@giovannizotta that was the point of this ticket.

I'm using lnbits, but found the needed circular payment option is not available on c-lightning where LND has an option for it. 
So just wondering if c-lightning can get this option, maybe through a plugin like this one.

https://github.com/ElementsProject/lightning/issues/6363
