### ISSUE TITLE
Suspect this plugin is broken on CLN 23.05

### ISSUE THREAD

**Issue by ghost** [giovannizotta/circular#17]
Getting this error message trying to load the plugin on startup:

> 2023-05-25T15:26:14.250Z INFO    plugin-circular: 15:26:14 node.go:69: GetInfo failed in init, exiting: json: cannot unmarshal number into Go struct field NodeInfo.fees_collected_msat of type string

Note I recompiled with this on line 69 of node.go to get more info on the error:

`log.Fatalf("GetInfo failed in init, exiting: %s", err.Error())`

I just saw msat and assumed this had something to do with the great msat migration :P

**Comment by tsjk** [comment]
Yes. It is. Along with a lot of other plugins.
CLN is still immature. Refrain from upgrading until you know that what you need works.
Hopefully this plugin gets updated soon.

**Comment by tsjk** [comment]
https://pastebin.com/LSErJRB7 - might work. I haven't tried it yet.
I don't know any Go. Just did what made sense from a generalist point of view.
My only question mark is that uint32-conversion - on 64-bit architectures that will not do a good thing if the delay is larger than 2^32. I'm not sure if that'll ever be a real issue...

**Comment by tsjk** [comment]
Doesn't quite work, however. It loads but fails to do a rebalance. :) I might give it another go.

**Comment by ghost** [comment]
> Doesn't quite work, however. It loads but fails to do a rebalance. :) I might give it another go.

🍿

If you give it another go, please keep us posted

**Comment by tsjk** [comment]
Yeah. I think it's ok now. You can do like (assuming you are in the directory containing the source code for `circular`):
```
wget -qO- 'https://pastebin.com/raw/LSErJRB7' | dos2unix | patch -p1 && \
go build -o circular cmd/circular/*.go
```
Then you can install (If you need to chmod/move the binary or something) and reload the plugin.
I just did a successful circular payment with it.

**Comment by tsjk** [comment]
Not sure it was worth the bother. There are other plugins that are similar. But I have some bash scripts that wrap around this, so I thought I'd give it a peek. I took the opportunity and upgraded some deps while at it.

**Comment by ghost** [comment]
Worked for me :) 
I'll check out the other plugins

**Comment by tsjk** [comment]
I could do a PR. But I kind of doubt the project owner would care. I think interested parties can just patch and compile, and if the owner regains interest he can use the patch as well.

**Comment by giovannizotta** [comment]
@tsjk If you have a fix, I'm really happy to review and merge a PR. I just haven't had the time or motivation to do it myself :)

**Comment by tsjk** [comment]
Mhm. Well. My patch is on pastebin. I'll try to find time to fork, apply and make an pr if nothing happens for a while.
Note that the patch is one-way, meaning that no backward compatibility is maintained.

**Comment by PsySc0rpi0n** [comment]
@tsjk do you allow me to create a patch and open the PR wit your changes? I would love to do it even if I didn't write the code. It would be my first real contribution to some project...

I will refer you as the owner of the patch.
What you think?

**Comment by tsjk** [comment]
Sure. Do it. I'm a consultant by occupation. No prestige here!

**Comment by giovannizotta** [comment]
Thanks a lot to the contributors! I merged the fix and tagged a new release.
