### ISSUE TITLE
Handle when the last hop changes fees to us

### ISSUE THREAD

**Issue by devastgh** [giovannizotta/circular#2]
Currently if the last hop changes (increases) its fees to us, circular ends in a loop.

My node had the correct remote fees, gossip reached me, but during multiple graph updates it was not picked up when calculating routes.
Route finding and htlcs were sent out with the old fee of the last hop, failing there with `wire_fee_insufficient`
But since it does not blacklist the last hop, once you find 2 viable routes, it will ping-pong failing between them, until attempts are reached.

**Comment by giovannizotta** [comment]
Now we refresh peer information in every attempt, so this shouldn't be a problem anymore.
Solved by 46d7c9315f93b1afd3d95167db38712bb90d06f0
