### ISSUE TITLE
Multipath rebalance should not pick an offline channel for candidate

### ISSUE THREAD

**Issue by devastgh** [giovannizotta/circular#6]
`lightning-cli listpeers` `connected` to see if the peer is connected.
`lightning-cli listchannels` `active` to see if a peers channel is active.
It's enoguh to check this when a candidate fired imo, we should not check this before every htlc is sent, as that would cost probably too much. If a candidate is not connected or the channel is not active in the proper direction, we should omit firing the candidate.

**Comment by giovannizotta** [comment]
Addressed by b25910ecf2d22ab2355be3fa0a522ed745934984, 3b33d71291c7cd6de777ab5f44ed133dfedc1d78 and 27ae71c326a2380966989989fa8d8d131cde0b93. Now every time we fire a rebalance, both in and out peers are connected and the channel is in state `CHANNELD_NORMAL`. There may be other issues related to this, so feel free to reopen with specific concerns. Thanks!
