### ISSUE TITLE
error installing plugin

### ISSUE THREAD

**Issue by BitromNO** [giovannizotta/circular#9]
tried running it as root and admin with sudo
Raspiblitz on pi4

`lightningd --plugin=/home/admin/circular circular --circular-graph-refresh=5 --circular-peer-refresh=60 --circular-liquidity-refresh=120 --circular-save-stats=false --log-level=debug:plugin-circular`

error starting plugin '/home/admin/circular': opening pipe: Permission denied

**Comment by giovannizotta** [comment]
Hi, make sure the file is executable:
```
chmod +x circular
```
Will add that to the readme, thanks for the issue, let me know if this fixes it

**Comment by devastgh** [comment]
> tried running it as root and admin with sudo Raspiblitz on pi4
> 
> `lightningd --plugin=/home/admin/circular circular --circular-graph-refresh=5 --circular-peer-refresh=60 --circular-liquidity-refresh=120 --circular-save-stats=false --log-level=debug:plugin-circular`
> 
> error starting plugin '/home/admin/circular': opening pipe: Permission denied

Also, the command is probably wrong.
`lightningd --plugin=/home/admin/circular/circular --circular-graph-refresh=5 --circular-peer-refresh=60 --circular-liquidity-refresh=120 --circular-save-stats=false --log-level=debug:plugin-circular`

While lightningd can be started like this, i advise you to actually use a config file (Probably raspiblitz does it that way, you need to check). should be located in the home directory of the user running it in `~/.lightningd/` with a file name of `config` , unless raspiblitz puts is elsewhere. You should dig up in raspiblitz docs where it is.

**Comment by giovannizotta** [comment]
Thanks @devastgh, the purpose of that example was to show how to use startup options, not a recommended way indeed. I'll make it more clear
